name: flutter_getx_app
description: A Flutter GetX App with theming and translations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  permission_handler: ^11.3.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  country_flags: ^3.2.0
  image_picker: ^1.1.2
  file_picker: ^6.1.6
  fl_chart: ^0.65.0
  intl: ^0.20.2
  multi_dropdown: ^3.0.1
  excel: ^4.0.6
  multi_select_flutter: ^4.1.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Degular
      fonts:
        - asset: assets/fonts/DegularDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/DegularDisplay-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/DegularDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/DegularDisplay-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/DegularDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/DegularDisplay-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/DegularDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/DegularDisplay-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/DegularDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/DegularDisplay-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/DegularDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/DegularDisplay-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/DegularDisplay-Black.otf
          weight: 900
        - asset: assets/fonts/DegularDisplay-BlackItalic.otf
          weight: 900
          style: italic
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
